### ISSUE TITLE
cairo-vm version

### ISSUE THREAD

**Issue by piniom** [cartridge-gg/http-prover#53]
Why are we using an old cairo-vm version in the docker build?
https://github.com/cartridge-gg/http-prover/blob/4643ebfdfbd4f501a57a07d24541e7526b65d98e/Dockerfile#L21
The latest commit hash is `ed3117098dd33c96056880af6fa67f9b2caebfb4`

**Comment by chudkowsky** [comment]
there is not any particular reason for that, it would be good to bump this
